[project]
name = "pylogs"
description = "A simple library for CLI logging"
requires-python = ">=3.12.3"
version = "1.4.6"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "SimKDT" },
]
dependencies = [
    "tqdm"
]

[project.urls]
Homepage = "https://github.com/SimKDT/pylogs"
Issues = "https://github.com/SimKDT/pylogs/issues"
